### PR TITLE
parallel fetching & compositing of remote tile images

### PR DESCRIPTION
**Pull request by incanus**
This adds parallelization of the multi-image fetches for web tile sources. They are fetched in a dispatch group, with a configurable number of retries each (defaults to 3) and a configurable wait time for the whole group to finish (default of 2 seconds). Then all successful images are composited using the original routine before the final image is returned.

### CODE REVIEW

**Comment by trasch** [comment]
Thank you for the patch!

**Comment by cellininicholas** [comment]
Hey, this is great! 
But wouldn't it be great to have some code to handle 404s or incomplete requests for tile images?

Or does it already handle that?

**Comment by trasch** [comment]
In theory, it should deliver the error tile:

``` objc
    if (!image)
        return [RMTileImage errorTile];
```

**Comment by cellininicholas** [comment]
Often, the current method used for downloading tiles:
tileData = [NSData dataWithContentsOfURL:currentURL options:NSDataReadingUncached error:nil];

does not return nil when a download fails halfway, it would be better if we used an ASI framework with delegate methods, so we can handle such events.

**Comment by trasch** [comment]
I currently use ASIHttpRequest in my projects, but since it is not maintained anymore, I will switch to AFNetwork some time in the future. I will rewrite the route-me tile downloading then as well.

**Comment by incanus** [comment]
Why not just use `NSURLConnection`? There are some new block-based methods and in general, it's pretty robust these days.

**Comment by trasch** [comment]
Added issue #23.

**Pull request merged**
